try(require(shiny) || install.packages("shiny"))
try(require(udpipe) || install.packages("udpipe"))
try(require(textrank) || install.packages("textrank"))
try(require(lattice) || install.packages("lattice"))
try(require(igraph)|| install.packages("igraph"))
try(require(ggraph)|| install.packages("ggraph"))
try(require(ggplot2)|| install.packages("ggplot2"))
try(require(wordcloud) || install.packages("wordcloud"))
try(require(stringr) || install.packages("stringr"))
try(require(magrittr) || install.packages("magrittr"))
try(require(tidytext) || install.packages("tidytext"))
try(require(dplyr) || install.packages("dplyr"))
try(require(tidyr) || install.packages("tidyr"))



library(shiny)
library(udpipe)
library(textrank)
library(lattice)
library(igraph)
library(ggraph)
library(ggplot2)
library(wordcloud)
library(stringr)
library(magrittr)
library(tidytext)
library(dplyr)
library(tidyr)
