# Team Members:
# Ashutosh Sunar (1181 0017)
# Deepa Prakash (1181 0128)
# Sundeep Vachhani (1181 0086)

try(require(shiny) || install.packages("shiny"))
try(require(udpipe) || install.packages("udpipe"))
try(require(textrank) || install.packages("textrank"))
try(require(lattice) || install.packages("lattice"))
try(require(igraph)|| install.packages("igraph"))
try(require(ggraph)|| install.packages("ggraph"))
try(require(ggplot2)|| install.packages("ggplot2"))
try(require(wordcloud) || install.packages("wordcloud"))
try(require(stringr) || install.packages("stringr"))
try(require(magrittr) || install.packages("magrittr"))
try(require(tidytext) || install.packages("tidytext"))
try(require(dplyr) || install.packages("dplyr"))
try(require(tidyr) || install.packages("tidyr"))
try(require(slam) || install.packages("slam"))
try(require(text2vec) || install.packages("text2vec"))


library(shiny)
library(udpipe)
library(textrank)
library(lattice)
library(igraph)
library(ggraph)
library(ggplot2)
library(wordcloud)
library(stringr)
library(magrittr)
library(tidytext)
library(dplyr)
library(tidyr)
library(slam)
library(text2vec)
